# Generated by Django 4.1 on 2022-10-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumreply',
            old_name='post',
            new_name='discussion',
        ),
    ]
