# Generated by Django 4.1 on 2022-10-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0003_nestedreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_forum.forumreply'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_forum.forumdiscussion'),
        ),
        migrations.DeleteModel(
            name='NestedReply',
        ),
    ]
