# Generated by Django 4.1 on 2022-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0004_forumreply_reply_alter_forumreply_discussion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='replying_to',
            field=models.TextField(null=True),
        ),
    ]
