# Generated by Django 4.1 on 2022-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0005_forumreply_replying_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumreply',
            name='replying_to',
            field=models.TextField(default=''),
        ),
    ]
